### ISSUE TITLE
Polls open button

### ISSUE THREAD

**Issue by tolgahanuzun** [emre/dpoll.xyz#20]
The survey button can offer a better experience for users to be in a visible place. I called 10 seconds to get the polls button.

<img width="318" alt="screen shot 2018-11-07 at 10 30 43" src="https://user-images.githubusercontent.com/10615529/48116777-3486c300-e278-11e8-869d-033437e0a720.png">

Of course, design should be considered better, it's just a simple show. :)

**Comment by emre** [comment]
Yeah, the current "create poll" button is kinda hidden. Would love to see a patch. :)

**Comment by tolgahanuzun** [comment]
This issue is over. :)
