### ISSUE TITLE
`Add more choices` bug

### ISSUE THREAD

**Issue by tolgahanuzun** [emre/dpoll.xyz#43]
Clicking this button will redirect to the top of the page each time. A simple html error. #href can fixed with redirection.

**Comment by emre** [comment]
go for it. :-)

**Comment by tolgahanuzun** [comment]
its coming: :)
![kapture 2018-11-16 at 10 04 30](https://user-images.githubusercontent.com/10615529/48603347-28d98180-e987-11e8-9f58-9377da1882bd.gif)
