### ISSUE TITLE
[suggestion] Separate multiple answers in Steem comments better

### ISSUE THREAD

**Issue by espoem** [emre/dpoll.xyz#91]
## Actual behaviour

When user selects multiple answers, the answers are not separated enough.

![image](https://user-images.githubusercontent.com/16621517/52435643-a4744600-2b12-11e9-80b3-e1dc4643e3cc.png)

## Expected behaviour

Multiple answers should be better separated from each other. Put space between them or write each on a separate line.

**Comment by emre** [comment]
Thinking about adding them with a bulleted list if there are multiple choices:

```
Voted for:
- x
- y
- z
```

What do you think?

**Comment by espoem** [comment]
That can work.

**Comment by emre** [comment]
Fixed.
